### ISSUE TITLE
GreetingItem and GreetingNewUserItem are not functioning or configurable

### ISSUE THREAD

**Issue by zrisher** [SEServerExtender/EssentialsPlugin#17]
Hi there,

Looking at the [greeting dialog settings](https://github.com/SEServerExtender/EssentialsPlugin#automated-join-messages-for-new-and-old-players) and [in-game chat commands for editing settings](https://github.com/SEServerExtender/EssentialsPlugin#automated-join-messages-for-new-and-old-players) it seems like I should be able to edit the `GreetingItem` and `GreetingNewUserItem` settings using the standard chat commands. These commands work great for me for `GreetingEnabled`, `GreetingMessage`, and I tested the array operations with `BackupItems` to make sure that wasn't the problem. 

But when I try: `/admin settings GreetingItem`

I get: `Server: Getting Value(s) for Setting: GreetingItem` and then a blank line. No description of the current values, but no warnings I'm using it incorrectly either. 

I've tried accessing the values as `GreetingItem.Enabled`, `GreetingItem.0`, `GreetingItem.1`, `GreetingItem.0.Enabled`, etc, nothing. None of the array operations return an error or a success message.

What are the proper chat commands to set this setting's values?

**Comment by zrisher** [comment]
These also don't seem to be picked up from editing the Essentials-Settings.xml files.

**Comment by dodexahedron** [comment]
I've never seen a greeting dialog work, even from before I picked up the project.
I'll look into that, eventually, but it'll be a lower priority than other things unless I get a lot of requests for it.
Regular greeting chat items do work, though.  Depending on the size of your world and how quickly a user actually gets into the game, they may miss those greetings, though.  Not a lot I can do about that in the current state of things.

**Comment by zrisher** [comment]
That makes sense. Yes, the reason I was looking to use these was to ensure the user actually say it, as well as the ability to display a lot of text at once and still have it be easily accessible. Understood this is low pri. I'll adjust the title of the ticket to reflect the underlying problem.

**Comment by stephen-cernota** [comment]
Hey Dox,

The greeting dialog feature is amazing, and high priority on my list, it allows you to send a longer amount of textual information to a new user, for instance:  Rules, Settings, Tips, etc. A lot of users just randomly join servers and do not read the servers website or steam group and then fill up the chat with a bunch of basic questions about the sever. The greeting dialog fits that communication need.

I wish I had more details (two admins with no tool upgrade documentation atm) but it has been somewhere a week or two ago, our greeting dialog stopped working.

**Comment by dodexahedron** [comment]
I'll be sure it makes it on my list.
I think turret management and a couple of other broken things are probably higher priority, at the moment, but this will be in my top 5.

**Comment by DigTron** [comment]
Strange, works fine for me on 5 servers using dodex's extender/esssentials and has done for weeks...and before using dodex's too.... there was a breif spell when the chat handler was skrewy (and so greeting was not working) but I think that was fixed by Tyrsis and Dodex individually... was around the time vrage.common.dll was dropped.

 I think your problem is with the chat commands. Are the settings changes showing in the xml file ?

Try altering the settings xml in a text editor if you dont have access to the gui, and upload to your server or ask your host to place the file. You will need to reset the server or reload the plugin (bad idea?) for the changes to be read by essentials...

Also if you edit the xml directly and then attempt to change a setting via gui or chat command your changes will be overwritten.

Here is a copy of my settings from one of the servers.

 			  <RestartWhenUnresponsive>true</RestartWhenUnresponsive>
			  <GreetingEnabled>true</GreetingEnabled>
			  <GreetingMessage>yadda yadda yadda</GreetingMessage>
			  <GreetingPublic>false</GreetingPublic>
			  <GreetingItem>
				<Enabled>true</Enabled>
				<Title>READ FIRST - FIND CONTENTS BELOW</Title>
				<Header>yadda yadda yadda</Header>
				<Contents>yadda yadda yadda 
			 
			 </Contents>
				<ButtonText>HAPPY HUNTING</ButtonText>
			  </GreetingItem>
			  <GreetingNewUserMessage>!!-Type /motd for info at any time</GreetingNewUserMessage>
			  <GreetingNewUserItem>
				<Enabled>true</Enabled>
				<Title>READ FIRST - FIND CONTENTS BELOW</Title>
				<Header>yadda yadda yadda</Header>
				<Contents>yadda yadda yaddda
			 
				</Contents>
				<ButtonText>HAPPY HUNTING</ButtonText>
			  </GreetingNewUserItem>
			  <BackupEnabled>true</BackupEnabled>

**Comment by zrisher** [comment]
@DigTron, thanks but I actually had already tried placing this info in my `Essentials-Settings.xml` file once I'd generated it by using some of the other settings commands. No dice. I also tried copying your GreetingItem and GreetingNewUserItem into my file, but it didn't work either (It actually seems to have caused a re-write of my config file, all my other values are gone. But I backed up.)

**Comment by DjKiDD** [comment]
I managed to get the dialog box working. Dialog is shown when motd message is given. I have it setup to send motd to new users to agree to a dialog box. If set it public it will show the words motd when a new player joins. You can also see the dialog by typing /motd into the chat with /info enabled (atleast I have it enabled, haven't tested without it...)

**Comment by zrisher** [comment]
@DjKiDD so which setting did you change? Or what command did you use to do it? 

Using the chat commands, mine are below:
```
GreetingEnabled = true
GreetingMessage = "Welcome to Gardens of Sajuuk! Type /info for info."
GreetingNewUserMessage = ""
GreetingPublic = false
GreetingItem = ? This responds to get with "" but doesn't change when set
GreetingItem.Enabled = ? Same as above
GreetingNewUserItem = ? Same as above
GreetingNewUserItem.Enabled = ? Same as above

InformationEnabled = true
InformationItems.0 = { Enabled: True, Subcommand: 'motd',
  Message: 'Welcome...', IntervalSeconds: 1800 }
```

I still think the problem has something to do with the fact that I can't set or access the GreetingItem property settings.

**Comment by DjKiDD** [comment]
I will post my config when I get home. I have never gotten a chat command to work for me. It acts all helpful giving possible us command but no information. I have resorted to changing the settings manually through the server extender plugin section.

**Comment by DjKiDD** [comment]
![244850_screenshots_2015-05-09_00001](https://cloud.githubusercontent.com/assets/870855/7551740/2f2a9bc6-f649-11e4-9d3e-3d7aa7b874f8.jpg)

http://pastebin.com/vJrJ8tB4 <-- FULL XML

Some observations.
In order to display the message you need to set the greeting to motd
Notice NewUserGreetingMessage is set to motd the result is the screen shot above when a new user connects to warn them about clean ups.

Just typing /motd into chat use to pop up the dialog as configured. It seems to only show "No MOTD dialog defined on the server" so not sure where to set that up now... but I swear it works for me.

**Comment by zrisher** [comment]
I'm unable to access the Extender GUI client as I'm on a server managed by SESM (hostaspace.com). So I need to be able to do this through chat commands or config file editing.

When you say "you need to set the greeting to motd", what do you mean exactly? Are you saying we should set `GreetingMessage = "motd"`? That's not the case in your pasted settings. I also don't see `NewUserGreetingMessage` anywhere in your settings, but I do see `GreetingNewUserItem` is set to the dialog box show in your screenshot. But again, I've tried pasting these into my xml settings with no effect. I can't edit them in-game.

**Comment by DjKiDD** [comment]
<GreetingNewUserMessage>motd</GreetingNewUserMessage> is what it is saved as in the XML I guess, I honestly did not look at it too hard.
I just happen to only want new users to see this message the very first time. It will display everytime I log in if I set <GreetingMessage> to motd 
As far as chat commands go I do not believe the admin commands work at all, at least not for me in game.

**Comment by DjKiDD** [comment]
`-<GreetingNewUserItem>`
 
`<Enabled>true</Enabled>`
 
`<Title>Alert!</Title>`
 
`<Header>Terms and Conditions</Header>`
 
`<Contents>Due to general lag related issues any ship that uses the default name will be deleted nightly at 4:20 AM</Contents>`
 
`<ButtonText>I won't bitch when my ship is deleted.</ButtonText>`
 
`</GreetingNewUserItem>`

Looks like you might be leaving out the `-<GreetingNewUserItem>` properties.

**Comment by DigTron** [comment]
Hey sorry I never came back, not sure if you got this sorted but a sure fire way of getting this to work is to edit your settings file like I described, restart your server, and it should post. Using /motd will show it again. Its also important to note that there are two sets of settings, one for users that are new and one for users who are not.

GreetingItem and GreetingNewUserItem contain

```xml
<Enabled>true</Enabled>    <!-- sets whether or not the message is enabled  -->
<Title>READ FIRST - FIND CONTENTS BELOW</Title>   <!-- Large text at the top of the window -->
<Header>yadda yadda yadda</Header>     <!-- Smaller text at the top of the window (below the Title) -->
<Contents>yadda yadda yadda </Contents> <!-- The main body of text -->
<ButtonText>HAPPY HUNTING</ButtonText>  <!-- ButtonText -->
```
Don't have experience with the chat commands your using to change the settings so I cant help there with any confidence. But ill mess with them at some point and see if/why they are/aren't working.

This #26 would allow you to reload the config from a chat command without having to reload the plug-in or restart the server.

**Comment by DigTron** [comment]
The original name "Unable to interact with GreetingItem and GreetingNewUserItem settings via chat " describes the issue better.

**Comment by zrisher** [comment]
I could never get this to work, despite editing settings exactly as described and restarting numerous times. That said, I've moved away from using Extender so if I'm the only person still having this issue this can be closed.

**Comment by joemorin73** [comment]
I use this myself.  Although it's been sporadic in the last update or two.

**Comment by SilentSymphony** [comment]
I've been using this since the beginning, It has never been 100% reliable for me.

My main servers map is getting pretty old now, With it some performance is sacrificed and the farther we go the less and less i see it popping up.

Any future improvements to this would be greatly appreciated.

**Comment by dodexahedron** [comment]
I really do think this has to do with people just missing it, due to how long it takes to load into the game.
The events that fire off the chat message happen before people are typically actually able to see in-game chat.
I'm not sure if there is anything I can do about it, server-side.  This may require interaction with a client-side plugin to make totally reliable.
