### ISSUE TITLE
Updates Per Second: 0

### ISSUE THREAD

**Issue by MescalineMonkey** [SEServerExtender/EssentialsPlugin#32]
It's been displaying 0 while the server is running for several updates now.

**Comment by dodexahedron** [comment]
Pretty constant 57-60 on my server.
Show me the command line you use to launch.

-----Original Message-----

**Comment by MescalineMonkey** [comment]
echo ========== EXTENDER START
C:\Games\SpaceEngineers\DedicatedServer64\SEServerExtender.exe autostart instance=Hardcore path=C:\ProgramData\SpaceEngineersDedicated\Hardcore restartOnCrash

57-60? With how many people?

**Comment by dodexahedron** [comment]
6, at the moment. 58UPS.

Our no-limits server has 4 online right now at 38UPS, which is...annoying to play in.

I'm going to make a debug build for you to see if I can narrow anything down about that behavior.  There's no reason whatsoever that shouldn't be working.  It really is its own timer and everything.

**Comment by MescalineMonkey** [comment]
My server used to run around 11-14 ups with 24 people in it. Lots of limits though, to keep the UPS up. I've made some changes that should increase that, but haven't been able to tell because the UPS has been showing 0 for a while now.

**Comment by DjKiDD** [comment]
I am also showing that when running the server from an instance that it shows 0 UPS even tho the server is running at 60 UPS as seen in game.

**Comment by dodexahedron** [comment]
UPS is only relevant per machine.  The UPS reported by your clients will not be the same as the UPS reported by the server (or at least it doesn't have to be).

**Comment by DigTron** [comment]
yea never mentioned but since you made changes to that counter dodex, it has always read 0 for me. Perhaps there is something in your test environment what we are missing or something else causing it.

I can tell you that none of my servers are in default installation directory, that goes for instances also.

Hope this helps but yea, most definitely hasn't been working since you changed it.

**Comment by SilentSymphony** [comment]
Same here

**Comment by DigTron** [comment]
Perhaps the manner it was changed is the cause, does it now reference libraries that were not originally part of the requirements? (Feel free to face palm if that sounds like nonsense)

People who come to chime in please state if it is or isn't working for you AND a little something about your setup, anything that comes to mind. For the moment weather or not you use default installation directories..because that's all I can think of :/

I can tell you that the machine in question has .NET v2.0.50727, v3, v3.5 and v4... let men know if there is anything else you would like to know.

**Comment by SilentSymphony** [comment]
I'm not using the default directory either, otherwise my setup is fairly standard.

**Comment by DigTron** [comment]
Sorry, I do have .NET 4.5 installed also.

**Comment by dodexahedron** [comment]
So everyone having this problem has SESE in a **different** folder than SE?

**Comment by dodexahedron** [comment]
Would someone be willing to hop on skype and do a screen share so I can get a little real-time troubleshooting in a broken environment?

**Comment by DigTron** [comment]
Was just testing and I think its our old friend autostart, after some fiddling I removed only it from my starting params and the clock worked fine when I hit go. Did this in the default dir structure and my own.

**Comment by DigTron** [comment]
Adding ...
```
if (m_server.IsRunning)
				_genericUpdateTimer.Start( );
```


to line 91 of "SEServerExtender\SEServerExtender.cs " pushing the rest down, appears to fix this for me. 

When GUI is initialised (by "public SEServerExtender( Server server )" ) , if the server is already running it starts the timer.

Again I'm very green so I cannot guarantee I haven't done something stupid.

**Comment by dodexahedron** [comment]
Yes, it's an autostart thing.

The only place the timer is started, in the current version, is when the start button is clicked.
I'll make the suggested change, as that's a valid fix.

**Comment by DigTron** [comment]
Nice, thanks!
