### ISSUE TITLE
/admin delete grids noownership nopower Stop the server running

### ISSUE THREAD

**Issue by SwApiy** [SEServerExtender/EssentialsPlugin#37]
run the command /admin delete grids noownership nopower
and the server shutdown

2015-05-22 17:44:40.2023|Info|Chat - Server: Operation deletes 12 grids
2015-05-22 17:44:40.454: Logging off Steam...
2015-05-22 17:44:40.454: Shutting down server...
2015-05-22 17:44:40.556: Done
2015-05-22 17:44:40.5613|Info|Server has stopped running
2015-05-22 17:44:40.5683|Info|Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a23417
78e8'
2015-05-22 17:44:40.5683|Info|Shutting down plugin: Dedicated Server Essentials
- 1.12.4.2418

#edit: Sry i mean /admin delete grids noownership nopower

**Comment by SilentSymphony** [comment]
My scans are working fine but if i /admin delete grids nopower, or noownership i get the same, I have not tried any other variables.

**Comment by SilentSymphony** [comment]
This seems to be resolved in the newest version.

**Comment by SilentSymphony** [comment]
Actually this seems to be showing up again now, I think it might have something to do with dynamic concealment, I'm going to do some tests when I get up and see if that's the case.

@SwApiy Are you using dynamic concealment too?

**Comment by dodexahedron** [comment]
Most likely this was a thread safety issue.
I'm not going to directly address this one, since the change away from using reflection is going to have a significant impact on these sorts of things, sometimes for the better and sometimes for the worse.  We'll have to deal with the new issues as they arise, and a lot of existing issues are no longer really worth investigating until their code has been re-written.

**Comment by dodexahedron** [comment]
I'm closing this for now, even though it's not technically "fixed," for the reason stated above.
Once reflection is gone, we can see if it still happens and then address it from there.
Thanks for the report.
