### ISSUE TITLE
Asteroid Streaming Debug Displaying without debug checked

### ISSUE THREAD

**Issue by SilentSymphony** [SEServerExtender/EssentialsPlugin#55]
Not really a big issue but as the title suggests the debug info from streaming the asteroids is being logged without the debug option checked, This information can be pretty hard to keep up with, If this could be changed so that it is only seen when the debug is checked it would be great.

**Comment by dodexahedron** [comment]
I didn't really inspect that code very deeply.
I'll go through and give better consideration to what should be logged at what level.
Any preliminary suggestions?

Also, as a side note, nothing in any of the code I've written has paid attention to that debug checkbox.  It's too coarse.  NLog uses the configuration in the nlog.config file, and can be set to any of the following: Fatal, Error, Warning, Info, Debug, Trace (in increasing order of spamminess).
I will honestly probably remove that debug checkbox in a future version, since I haven't been using it at all.

**Comment by SilentSymphony** [comment]
After some more thought, And seeing how useful having the voxel streaming information can be, Seriously this is a good way to catch those hackers that are plaguing servers, steamid bound to coardinate data on the same line allows me to locate who was where and at what time, Since they somehow edit peoples medbays and spawn at them, This should definitely be output to its own file in the logs folder if possible, perhaps if the log actions option is enabled, or its own option to enable its logging.

And I honestly never use the debug feature, I had enabled it while actually trying to debug some issues i was having before reporting to you but there is very little data in there besides grids being added, concealed, and some update information.
