### ISSUE TITLE
[BUG]Running '/admin scan grids' does not return all entities (Entities exist in SE Entities Tab) 

### ISSUE THREAD

**Issue by afinegan** [SEServerExtender/EssentialsPlugin#64]
I run:
/admin scan grids

Comes back with every entity except for 1 ship, I will post the ships prefab pastebin link below
If I demerge the the turrent pods off each side (merge block) - it shows up in the '/admin scan grids' again. I need this to work else whoever spawns in with that ship, the ship will litter the sky (I use the clean option built into SE) - I dont want the server Spawnship cleaner on, I want people to be able to sup up there spawnships without fear of deletion if they beacon it. Other spawnships selected on the same list spawn fine, this is the first spawnship in the list (there is 1 other spawnship with merge blocked components that works fine)

http://pastebin.com/dW0CwwSU

**Comment by afinegan** [comment]
I removed the connectors to the outer turrents and it now shows up in the scan grids list on spawn in. I guess when the vehicle spawns in and the merge blocks lock, it also locks the connectors. Locked connectors on a spawned ship removes itself from the /admin scan grids list.   Also some of the NPC cargo ships dont show up under the /admin scan grids list.

**Comment by FoxWyvern** [comment]
See post:
https://github.com/SEServerExtender/EssentialsPlugin/issues/52
scroll to bottom and check for reasons why grids will not conceal. besides antenna/beacon range, medbay reveal due to same faction with voxel conceal on, damaged beacons/antennas, and grids with working refinerys, all the listed others will cause the scan grids command to fail to report those grids back.
