### ISSUE TITLE
Server Waypoints, Faction Chat, MOTD... not working after most recent SE updates.

### ISSUE THREAD

**Issue by MescalineMonkey** [SEServerExtender/EssentialsPlugin#69]
Any ideas?

**Comment by niapet** [comment]
same here last two updates

**Comment by McyD** [comment]
Additionally as of 1.102 client crashes as soon as /wp toggle is used.

**Comment by SilentSymphony** [comment]
take a copy of your essentials settings then delete it and generate a fresh configuration file, it is very likely that your configuration is outdated, as all of these features appear to be working fine on my server.

**Comment by chaos234** [comment]
Since 01_104 - well, it's my first time using SESE with Essentials - I tried to place some WPs at server side. But after enabling the WP-System over the GUI from SESE the client crashes instantly after joining to the server.

Here is the error from the client log: http://hastebin.com/buzarelari.avrasm

So actually I can't use the WP-System and som other cmd's aren't working to (e. g. player list).
Hopefully that this and all other things will be fixed as soon as possible.

Otherwise the plugin still works fine with the latest SESE and SEGame.
