### ISSUE TITLE
BackupAsteroids recommendation?

### ISSUE THREAD

**Issue by yaccoin** [SEServerExtender/EssentialsPlugin#7]
This defaults to true, but I'm curious if there is any downside to setting it to false?  I've noticed my world file is growing, now at 9M, and am wondering how much of that is due to asteroids that were spawned by explorer ships?

My daily cleanup takes care of the explorers, but not the asteroids.  If I turned this to false, would they be cleaned up during the daily restarts?

**Comment by Lordicon** [comment]
If I am not mistake and you have "0" asteroids on the server which are central asteroids and the procedural density to around 0.15 with a random seed your world size should not be over 1MB. again if I am not mistaken the world size is growing only when players dig or change an asteroid in some way or another. So every asteroid that gets changes then becomes a static asteroid on the server and is no longer procedural. Static uses system resources where as procedural used none. So if you were to know which asteroids your players have on the server you could delete the asteroids that they dug in in the past making your servers world size go back down. Again not 100% on this its just my theory on how it all works.

**Comment by dodexahedron** [comment]
"World size" is a little misleading, though.
The "world size" reported by the game is only the size of the asteroids and doesn't have anything to do with all the ships you have, which are quite significant.  For example, world size on one of my servers is "7MB" but the actual sandbox file is 80MB.

In any case, @Lordicon you're correct that procedural asteroids are only saved as part of the persistent world if someone interacts with them.
However, during the course of running the game, once they are generated, they're part of the world and don't "de-spawn" until the game is shut down, as far as I can tell.  Therefore, removal can help.

@yaccoin, to answer your question, saves don't include them unless they have been interacted with, so turning off the asteroid backup won't help you.

I really don't recommend turning off asteroid backup, anyway.  Especially on your world, since you have structures built into the asteroids.  If you don't back up the asteroid, then a restore has a good chance of destroying structures built into asteroids, if they are procedural asteroids, or if parts of the asteroid were drilled out for construction.
