### ISSUE TITLE
Block Enforcement workaround/exploit

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/EssentialsPlugin#92]
Players have discovered ways to get around block enforcement in my server. I can understand if you a limited within the API to be able to fix it, but if you can, that'll be great. In the example below, a player had found that using advanced rotors worked quite well in getting around my 1 drill limit.

[http://i.imgur.com/dTePkQO.png](http://i.imgur.com/dTePkQO.png)

**Comment by rexxar-tc** [comment]
This is a tricky thing to deal with. I could use grid groups to find all blocks attached to the grid, but we hit a problem where if you dock ships with a connector, it will count that as a single group and delete blocks from both ships. I could work around the issue by excluding grids from the group attached by connectors, but then instead of rotors they'll just use connectors.

The only solution I can come up with is to implement block limits per player. Say you limit a player to one drill. Then they can only ever have one functional drill on one grid. You could get around this by attaching a drill owned by no one to a landing gear or something, but in that case I can find blocks near player grids with no ownership or NPC ownership and disable them.

The thing is, no matter how clever you get with stuff like this, players will always find a way around it.

**Comment by EngineerBean** [comment]
Just leave this one be then Rexxar, I can deal with it myself. So far, there has been only a small handful of players that have worked out the workaround. Thanks for your reply/feedback.
